services:
  mysql:
    container_name: container_datamind_bd
    image: anilmar/datamind_bd:1.0
    restart: always
    ports:
      - "3306:3306"
    networks:
      - app-network

  node:
    container_name: container_datamind_site
    image: anilmar/datamind:1.0
    restart: always
    ports:
      - "3333:3333"
    depends_on:
      - mysql
    networks:
      - app-network

  java:
    container_name: container_datamind_java
    image: anilmar/datamind_java:1.0
    restart: always
    depends_on:
      - mysql
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_SESSION_TOKEN: ${AWS_SESSION_TOKEN}
      NAME_BUCKET: ${NAME_BUCKET}
      DB_HOST: ${DB_HOST}
      DB_DATABASE: ${DB_DATABASE}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
