services:
  mysql:
    container_name: container_datamind_bd
    image: ryanzin1380/datamind_bd
    restart: always
    ports:
      - "3306:3306"

  node:
    container_name: container_datamind_site
    image: ryanzin1380/datamind
    restart: always
    ports:
      - "3333:3333"

  java:
    container_name: container_datamind_java
    image: anilmar/datamind_java:1.0
    restart: always
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_SESSION_TOKEN: ${AWS_SESSION_TOKEN}
      NAME_BUCKET: ${NAME_BUCKET}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
