# Usa a imagem base OpenJDK 21
FROM openjdk:21-slim

# Atualiza os pacotes, instala curl e cron
RUN apt-get update && apt-get install -y curl cron && apt-get clean

# Define o diretório de trabalho
WORKDIR /app

# Baixa o arquivo JAR do repositório e renomeia
RUN curl -o Projeto-JAVA.jar https://raw.githubusercontent.com/DataMind-SPTECH/Projeto-Java/main/Projeto-JAVA-1.0-SNAPSHOT-jar-with-dependencies.jar

# Cria um log para o cron
RUN touch /var/log/cron.log

# Comando para iniciar o cron e o log
CMD cron && tail -f /var/log/cron.log
